VSLBLDEX ; Living examples for VSLBLD — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLBLD label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleEnvCheck(.pass,.fail)
        do tExampleEnvCheck2(.pass,.fail)
        do tExampleLastError(.pass,.fail)
        do tExampleManifest(.pass,.fail)
        do tExampleManifest2(.pass,.fail)
        do tExampleManifest3(.pass,.fail)
        do tExampleRequireBase(.pass,.fail)
        do tExampleRequireBase2(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleEnvCheck(pass,fail)     ;@TEST "example: VSLBLD.envCheck"
        do true^STDASSERT(.pass,.fail,$$envCheck^VSLBLD(.facts)=1,"$$envCheck succeeds on a live VistA")
        quit
        ;
tExampleEnvCheck2(pass,fail)    ;@TEST "example: VSLBLD.envCheck"
        set ok=$$envCheck^VSLBLD(.facts) do true^STDASSERT(.pass,.fail,$get(facts("engine"))'="","env-check reports the engine type")
        quit
        ;
tExampleLastError(pass,fail)    ;@TEST "example: VSLBLD.lastError"
        do raises^STDASSERT(.pass,.fail,"set x=$$requireBase^VSLBLD("""")","U-VSL-BLD-ARG","arming the error state") do true^STDASSERT(.pass,.fail,$$lastError^VSLBLD()'="","lastError carries the malformed-call detail after a rejected call")
        quit
        ;
tExampleManifest(pass,fail)     ;@TEST "example: VSLBLD.manifest"
        do true^STDASSERT(.pass,.fail,$$manifest^VSLBLD(.out)'<5,"the base ships at least the five M1-M4 VSL* modules")
        quit
        ;
tExampleManifest2(pass,fail)    ;@TEST "example: VSLBLD.manifest"
        set n=$$manifest^VSLBLD(.out) do true^STDASSERT(.pass,.fail,$get(out("requiredBuild"))="MSL*0.1*1","manifest declares the Required Build on the m-stdlib base")
        quit
        ;
tExampleManifest3(pass,fail)    ;@TEST "example: VSLBLD.manifest"
        set n=$$manifest^VSLBLD(.out) do true^STDASSERT(.pass,.fail,$get(out("patch"))="VSL*1.0*3","manifest declares the patch identity VSL*1.0*3")
        quit
        ;
tExampleRequireBase(pass,fail)  ;@TEST "example: VSLBLD.requireBase"
        do true^STDASSERT(.pass,.fail,$$requireBase^VSLBLD("ZZNOSUCH*9.9*9")=0,"an absent base build is a normal 0 (a not-installed result, not a loud failure)")
        quit
        ;
tExampleRequireBase2(pass,fail) ;@TEST "example: VSLBLD.requireBase"
        do raises^STDASSERT(.pass,.fail,"set x=$$requireBase^VSLBLD("""")","U-VSL-BLD-ARG","$$requireBase with no build name raises U-VSL-BLD-...")
        quit
        ;
