VSLCFGEX ; Living examples for VSLCFG — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLCFG label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleGet(.pass,.fail)
        do tExampleGetEffective(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleGet(pass,fail)          ;@TEST "example: VSLCFG.get"
        do eq^STDASSERT(.pass,.fail,$$get^VSLCFG("ZZVSLCFGNOSUCH","fallback"),"fallback","get: unset parameter returns the default")
        quit
        ;
tExampleGetEffective(pass,fail) ;@TEST "example: VSLCFG.getEffective"
        do eq^STDASSERT(.pass,.fail,$$getEffective^VSLCFG("ZZVSLCFGNOSUCH","fb"),"fb","getEffective: unset parameter returns the default")
        quit
        ;
