VSLENVEX ; Living examples for VSLENV — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLENV label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleCheck(.pass,.fail)
        do tExampleCheck2(.pass,.fail)
        do tExampleCheck3(.pass,.fail)
        do tExampleKernelVer(.pass,.fail)
        do tExampleTlsConfig(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleCheck(pass,fail)        ;@TEST "example: VSLENV.check"
        set x=$$check^VSLENV(.facts) do eq^STDASSERT(.pass,.fail,x,1,"check returns 1")
        quit
        ;
tExampleCheck2(pass,fail)       ;@TEST "example: VSLENV.check"
        set x=$$check^VSLENV(.facts) do true^STDASSERT(.pass,.fail,facts("engine")'="","check fills a non-empty engine fact")
        quit
        ;
tExampleCheck3(pass,fail)       ;@TEST "example: VSLENV.check"
        set x=$$check^VSLENV(.facts) do eq^STDASSERT(.pass,.fail,facts("version"),$zversion,"check reports the running engine version")
        quit
        ;
tExampleKernelVer(pass,fail)    ;@TEST "example: VSLENV.kernelVer"
        do true^STDASSERT(.pass,.fail,$$kernelVer^VSLENV()'="","kernelVer is non-empty on a Kernel-equipped VistA")
        quit
        ;
tExampleTlsConfig(pass,fail)    ;@TEST "example: VSLENV.tlsConfig"
        do eq^STDASSERT(.pass,.fail,$$tlsConfig^VSLENV(),$$GET^XPAR("SYS","DEFAULT TLS SERVER CONFIG",1),"tlsConfig reads the DEFAULT TLS SERVER CONFIG parameter")
        quit
        ;
