VSLFSEX ; Living examples for VSLFS — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLFS label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleExists(.pass,.fail)
        do tExampleExists2(.pass,.fail)
        do tExampleGet(.pass,.fail)
        do tExampleGet2(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleExists(pass,fail)       ;@TEST "example: VSLFS.exists"
        set DUZ=1,DUZ(0)="@",U="^",DT=$$DT^XLFDT do eq^STDASSERT(.pass,.fail,$$exists^VSLFS(200,"1,"),1,"exists: #200 IEN 1 (postmaster) exists")
        quit
        ;
tExampleExists2(pass,fail)      ;@TEST "example: VSLFS.exists"
        set DUZ=1,DUZ(0)="@",U="^",DT=$$DT^XLFDT do eq^STDASSERT(.pass,.fail,$$exists^VSLFS(200,"999999999,"),0,"exists: an absent record returns 0")
        quit
        ;
tExampleGet(pass,fail)          ;@TEST "example: VSLFS.get"
        set DUZ=1,DUZ(0)="@",U="^",DT=$$DT^XLFDT do true^STDASSERT(.pass,.fail,$$get^VSLFS(200,"1,",".01","")'="","get: #200 IEN 1 (.01) reads a non-empty name")
        quit
        ;
tExampleGet2(pass,fail)         ;@TEST "example: VSLFS.get"
        set DUZ=1,DUZ(0)="@",U="^",DT=$$DT^XLFDT do eq^STDASSERT(.pass,.fail,$$get^VSLFS(200,"999999999,",".01","MISS"),"MISS","get: an absent record returns the default")
        quit
        ;
