VSLHL7TAPEX ; Living examples for VSLHL7TAP — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLHL7TAP label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleCursor(.pass,.fail)
        do tExampleCursor2(.pass,.fail)
        do tExampleReadHLO(.pass,.fail)
        do tExampleReadLegacy(.pass,.fail)
        do tExampleReadLegacy2(.pass,.fail)
        do tExampleResetCursors(.pass,.fail)
        do tExampleSetCursor(.pass,.fail)
        do tExampleTail(.pass,.fail)
        do tExampleTail2(.pass,.fail)
        do tExampleTailHLO(.pass,.fail)
        do tExampleTailLegacy(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleCursor(pass,fail)       ;@TEST "example: VSLHL7TAP.cursor"
        kill ^VSLTAP("hl7cur","772")  do eq^STDASSERT(.pass,.fail,$$cursor^VSLHL7TAP("772"),0,"an unset cursor reads as 0")
        quit
        ;
tExampleCursor2(pass,fail)      ;@TEST "example: VSLHL7TAP.cursor"
        set ^VSLTAP("hl7cur","778")=4242  do eq^STDASSERT(.pass,.fail,$$cursor^VSLHL7TAP("778"),4242,"cursor returns the persisted high-water IEN")  kill ^VSLTAP("hl7cur","778")
        quit
        ;
tExampleReadHLO(pass,fail)      ;@TEST "example: VSLHL7TAP.readHLO"
        set ^HLB(50,0)="MSGID123^900^^O^link",^HLB(50,1)="MSH|^~\&|APP|FAC|",^HLB(50,2)="DEST|FAC2",^HLA(900,1,1,0)="EVN|A01",^HLA(900,1,2,0)="PID|1||12345"  do eq^STDASSERT(.pass,.fail,$$readHLO^VSLHL7TAP(50),"MSH|^~\&|APP|FAC|DEST|FAC2"_$char(13)_"EVN|A01"_$char(13)_"PID|1||12345","MSH(nodes 1+2) prepended to the #777 body segments, CR-delimited, byte-verbatim")
        quit
        ;
tExampleReadLegacy(pass,fail)   ;@TEST "example: VSLHL7TAP.readLegacy"
        set ^HL(772,100,"IN",1,0)="MSH|^~\&|ROR SITE",^HL(772,100,"IN",2,0)="PID|1||0",^HL(772,100,"IN",3,0)="CSR|VA HEPC"  do eq^STDASSERT(.pass,.fail,$$readLegacy^VSLHL7TAP(100),"MSH|^~\&|ROR SITE"_$char(13)_"PID|1||0"_$char(13)_"CSR|VA HEPC","the three #772 'IN' segments rejoin byte-verbatim, CR-delimited")
        quit
        ;
tExampleReadLegacy2(pass,fail)  ;@TEST "example: VSLHL7TAP.readLegacy"
        set ^HL(772,200,0)="3170717.234501^^^^^5002230648"  do eq^STDASSERT(.pass,.fail,$$readLegacy^VSLHL7TAP(200),"","a purged #772 entry (header only, no 'IN' body) returns the empty string")
        quit
        ;
tExampleResetCursors(pass,fail) ;@TEST "example: VSLHL7TAP.resetCursors"
        set ^VSLTAP("hl7cur","772")=5,^VSLTAP("hl7cur","778")=9  do resetCursors^VSLHL7TAP()  do eq^STDASSERT(.pass,.fail,$$cursor^VSLHL7TAP("772")+$$cursor^VSLHL7TAP("778"),0,"resetCursors clears both cursors back to 0")
        quit
        ;
tExampleSetCursor(pass,fail)    ;@TEST "example: VSLHL7TAP.setCursor"
        do setCursor^VSLHL7TAP("772",99)  do eq^STDASSERT(.pass,.fail,$$cursor^VSLHL7TAP("772"),99,"setCursor persists the high-water IEN, read back by $$cursor")  kill ^VSLTAP("hl7cur","772")
        quit
        ;
tExampleTail(pass,fail)         ;@TEST "example: VSLHL7TAP.tail"
        kill ^VSLTAP,^XTMP("VSLTAP"),^HL(772),^HLB,^HLA  do arm^VSLTAP(),setConsumer^VSLTAP(1)  set ^HL(772,10,0)="3170627.01^^^O^^L1^^10^D",^HL(772,10,"IN",1,0)="MSH|leg",^HL(772,10,"IN",0)="^^1^1^3170627^"  set ^HLB(3,0)="H1^200^^O^link",^HLB(3,1)="MSH|^~\&|",^HLB(3,2)="|ADT",^HLA(200,1,1,0)="EVN|hlo",^HLA(200,1,0)="^^1^1^3170627^"  do tail^VSLHL7TAP()  do eq^STDASSERT(.pass,.fail,$$size^VSLTAP(),2,"one tail pass drains both the legacy and the HLO store")
        quit
        ;
tExampleTail2(pass,fail)        ;@TEST "example: VSLHL7TAP.tail"
        kill ^VSLTAP,^XTMP("VSLTAP"),^HL(772)  do arm^VSLTAP()  set ^HL(772,10,0)="3170627^^^O^^L1^^10^D",^HL(772,10,"IN",1,0)="MSH|x",^HL(772,10,"IN",0)="^^1^1^3170627^"  do tail^VSLHL7TAP()  do eq^STDASSERT(.pass,.fail,$$size^VSLTAP(),0,"no consumer -> zero capture, cursor frozen for catch-up on re-arm")
        quit
        ;
tExampleTailHLO(pass,fail)      ;@TEST "example: VSLHL7TAP.tailHLO"
        kill ^VSLTAP,^XTMP("VSLTAP"),^HLB,^HLA  do arm^VSLTAP(),setConsumer^VSLTAP(1)  set ^HLB(7,0)="MID^400^^O^link",^HLB(7,1)="MSH|^~\&|X|",^HLB(7,2)="Y||ADT^A01|MID|P|2.4",^HLA(400,1,1,0)="EVN|A01",^HLA(400,1,0)="^^1^1^3170627^"  do tailHLO^VSLHL7TAP()  do eq^STDASSERT(.pass,.fail,$$cursor^VSLHL7TAP("778"),7,"the #778 cursor advances after tailing the HLO entry")
        quit
        ;
tExampleTailLegacy(pass,fail)   ;@TEST "example: VSLHL7TAP.tailLegacy"
        kill ^VSLTAP,^XTMP("VSLTAP"),^HL(772)  do arm^VSLTAP(),setConsumer^VSLTAP(1)  set ^HL(772,2230625,0)="3170627.01^^^O^^ID1^^2230625^D",^HL(772,2230625,"IN",1,0)="MSH|^~\&|A",^HL(772,2230625,"IN",0)="^^1^1^3170627^"  set ^HL(772,2230648,0)="3170627.01^^^I^^ID2^^2230648^D",^HL(772,2230648,"IN",1,0)="MSH|^~\&|B",^HL(772,2230648,"IN",0)="^^1^1^3170627^"  do tailLegacy^VSLHL7TAP()  do eq^STDASSERT(.pass,.fail,$$cursor^VSLHL7TAP("772"),2230648,"the #772 cursor advances to the last IEN after tailing both entries")
        quit
        ;
