VSLIOEX ; Living examples for VSLIO — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLIO label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleConnect(.pass,.fail)
        do tExampleConnectTls(.pass,.fail)
        do tExampleTlsAvailable(.pass,.fail)
        do tExampleTlsHelp(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleConnect(pass,fail)      ;@TEST "example: VSLIO.connect"
        do true^STDASSERT(.pass,.fail,$$connect^VSLIO("127.0.0.1",65000,2)=0,"connect to a closed port returns 0 (POP positive)")
        quit
        ;
tExampleConnectTls(pass,fail)   ;@TEST "example: VSLIO.connectTls"
        do raises^STDASSERT(.pass,.fail,"set x=$$connectTls^VSLIO(""h"",1,1,""cfg"")","U-VSLIO-NOTLS","connectTls raises U-VSLIO-NOTLS")
        quit
        ;
tExampleTlsAvailable(pass,fail) ;@TEST "example: VSLIO.tlsAvailable"
        do eq^STDASSERT(.pass,.fail,$$tlsAvailable^VSLIO(),0,"example: VSLIO.tlsAvailable")
        quit
        ;
tExampleTlsHelp(pass,fail)      ;@TEST "example: VSLIO.tlsHelp"
        do contains^STDASSERT(.pass,.fail,$$tlsHelp^VSLIO(),"NOTLS","tlsHelp carries the remediation message")
        quit
        ;
