VSLRPCWRAPEX ; Living examples for VSLRPCWRAP — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLRPCWRAP label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleCtx(.pass,.fail)
        do tExampleCtx2(.pass,.fail)
        do tExampleParams(.pass,.fail)
        do tExampleReq(.pass,.fail)
        do tExampleReqWork(.pass,.fail)
        do tExampleResp(.pass,.fail)
        do tExampleResult(.pass,.fail)
        do tExampleResult2(.pass,.fail)
        do tExampleResult3(.pass,.fail)
        do tExampleResult4(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleCtx(pass,fail)          ;@TEST "example: VSLRPCWRAP.ctx"
        new rec,DUZ,XWBTIP,XWBTSKT set DUZ=168,XWBTIP="10.1.2.3",XWBTSKT=51001 do ctx^VSLRPCWRAP(.rec) do eq^STDASSERT(.pass,.fail,rec("client"),"10.1.2.3:51001","client = XWBTIP:XWBTSKT (FU-18)")
        quit
        ;
tExampleCtx2(pass,fail)         ;@TEST "example: VSLRPCWRAP.ctx"
        new rec,DUZ,XWBTIP,XWBTSKT set DUZ=168 do ctx^VSLRPCWRAP(.rec) do eq^STDASSERT(.pass,.fail,rec("duz"),168,"duz read from DUZ; job = $job")
        quit
        ;
tExampleParams(pass,fail)       ;@TEST "example: VSLRPCWRAP.params"
        new XWB set XWB(3,"P",1)="ALPHA",XWB(3,"P",2)="9",XWB(3,"P",3)="" do eq^STDASSERT(.pass,.fail,$$params^VSLRPCWRAP(),"ALPHA"_$char(1)_"9"_$char(1)_"","params $C(1)-joined verbatim in subscript order")
        quit
        ;
tExampleReq(pass,fail)          ;@TEST "example: VSLRPCWRAP.req"
        new h,hdr,ok,XWB,XWBSEC tstart ():transactionid="batch" set XWB(2,"CAPI")="ORWPT LIST ALL",XWBSEC="",^VSLTAP("cfg","s3station")="500" do arm^VSLTAP(),setConsumer^VSLTAP(1),req^VSLRPCWRAP() set h=$$head^VSLTAP(),ok=$$hdr^VSLTAP(h,.hdr) do eq^STDASSERT(.pass,.fail,hdr("direction"),"req","req emits one dir=req record (rolled back via tstart/trollback)") trollback
        quit
        ;
tExampleReqWork(pass,fail)      ;@TEST "example: VSLRPCWRAP.reqWork"
        new h,hdr,ok,XWB,XWBSEC tstart ():transactionid="batch" set XWB(2,"CAPI")="ORWU NEWPERS",XWBSEC="",^VSLTAP("cfg","s3station")="500" do arm^VSLTAP(),setConsumer^VSLTAP(1),reqWork^VSLRPCWRAP() set h=$$head^VSLTAP(),ok=$$hdr^VSLTAP(h,.hdr) do eq^STDASSERT(.pass,.fail,hdr("rpc"),"ORWU NEWPERS","reqWork builds the req rec carrying the XWB CAPI rpc name (rolled back)") trollback
        quit
        ;
tExampleResp(pass,fail)         ;@TEST "example: VSLRPCWRAP.resp"
        new h,hdr,ok,XWB,XWBSEC,XWBP,XWBPTYPE tstart ():transactionid="batch" set XWB(2,"CAPI")="ORWPT LIST ALL",XWBSEC="",XWBP="result",XWBPTYPE=1,^VSLTAP("cfg","s3station")="500" do arm^VSLTAP(),setConsumer^VSLTAP(1),req^VSLRPCWRAP(),resp^VSLRPCWRAP() set h=$$head^VSLTAP(),ok=$$hdr^VSLTAP(h,.hdr) do eq^STDASSERT(.pass,.fail,hdr("direction"),"resp","resp emits a dir=resp record on the success path (rolled back)") trollback
        quit
        ;
tExampleResult(pass,fail)       ;@TEST "example: VSLRPCWRAP.result"
        new rec,XWBPTYPE,XWBP set XWBPTYPE=1,XWBP="hello" do result^VSLRPCWRAP(.rec) do eq^STDASSERT(.pass,.fail,rec("result_kind"),"scalar","XWBPTYPE=1 -> result_kind=scalar")
        quit
        ;
tExampleResult2(pass,fail)      ;@TEST "example: VSLRPCWRAP.result"
        new rec,XWBPTYPE,XWBP set XWBPTYPE=1,XWBP="hello" do result^VSLRPCWRAP(.rec) do eq^STDASSERT(.pass,.fail,rec("payload"),"hello","scalar payload = the verbatim XWBP value")
        quit
        ;
tExampleResult3(pass,fail)      ;@TEST "example: VSLRPCWRAP.result"
        new rec,XWBPTYPE,XWBP set XWBPTYPE=4,XWBP="^TMP($J,""X"")" do result^VSLRPCWRAP(.rec) do eq^STDASSERT(.pass,.fail,rec("result_kind"),"global","XWBPTYPE=4 -> result_kind=global, gref = the closed-root ref")
        quit
        ;
tExampleResult4(pass,fail)      ;@TEST "example: VSLRPCWRAP.result"
        new rec,XWBPTYPE set XWBPTYPE=2 do result^VSLRPCWRAP(.rec) do eq^STDASSERT(.pass,.fail,rec("gref"),"XWBP","XWBPTYPE=2 (table) -> gref=XWBP (a LOCAL array tree)")
        quit
        ;
