VSLSECEX ; Living examples for VSLSEC — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLSEC label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleBySecid(.pass,.fail)
        do tExampleDuz(.pass,.fail)
        do tExampleHasKey(.pass,.fail)
        do tExampleHasKey2(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleBySecid(pass,fail)      ;@TEST "example: VSLSEC.bySecid"
        do raises^STDASSERT(.pass,.fail,"set x=$$bySecid^VSLSEC("""")","U-VSL-SEC-ARG","$$bySecid("""") raises U-VSL-SEC-...")
        quit
        ;
tExampleDuz(pass,fail)          ;@TEST "example: VSLSEC.duz"
        new DUZ set DUZ=1 do eq^STDASSERT(.pass,.fail,$$duz^VSLSEC(),1,"$$duz returns the ambient DUZ (NEWed, no side effect)")
        quit
        ;
tExampleHasKey(pass,fail)       ;@TEST "example: VSLSEC.hasKey"
        do eq^STDASSERT(.pass,.fail,$$hasKey^VSLSEC("ZZ NO SUCH KEY",1),0,"hasKey is 0 (a normal DENY) for an unheld key")
        quit
        ;
tExampleHasKey2(pass,fail)      ;@TEST "example: VSLSEC.hasKey"
        do raises^STDASSERT(.pass,.fail,"set x=$$hasKey^VSLSEC("""",1)","U-VSL-SEC-ARG","$$hasKey with an empty key raises U-VSL-SEC-...")
        quit
        ;
