VSLS3EX ; Living examples for VSLS3 — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLS3 label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleCtx(.pass,.fail)
        do tExampleDrain(.pass,.fail)
        do tExampleEnvelope(.pass,.fail)
        do tExampleEnvelope2(.pass,.fail)
        do tExampleEnvelope3(.pass,.fail)
        do tExampleEnvelope4(.pass,.fail)
        do tExampleEnvelope5(.pass,.fail)
        do tExampleEnvelope6(.pass,.fail)
        do tExampleEnvelope7(.pass,.fail)
        do tExampleFidelityKey(.pass,.fail)
        do tExampleGSerialize(.pass,.fail)
        do tExampleKey(.pass,.fail)
        do tExampleKey2(.pass,.fail)
        do tExampleOffWindowsKey(.pass,.fail)
        do tExampleResolveRec(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleCtx(pass,fail)          ;@TEST "example: VSLS3.ctx"
        new ctx,opt,b,save merge save=^VSLTAP("cfg") kill ^VSLTAP("cfg") set ^VSLTAP("cfg","s3bucket")="vista-traffic",^VSLTAP("cfg","s3endpoint")="http://m-s3-minio:9000" set b=$$ctx^VSLS3(.ctx,.opt) kill ^VSLTAP("cfg") merge ^VSLTAP("cfg")=save do eq^STDASSERT(.pass,.fail,b,"vista-traffic","bucket + endpoint read from the ^VSLTAP config seam (set-then-restore)")
        quit
        ;
tExampleDrain(pass,fail)        ;@TEST "example: VSLS3.drain"
        new res,save,csave merge save=^XTMP("VSLTAP") merge csave=^VSLTAP("cfg") kill ^XTMP("VSLTAP"),^VSLTAP("cfg") set ^VSLTAP("cfg","s3sink")="capture",^VSLTAP("cfg","mode")="armed",^VSLTAP("cfg","consumer")=1,^VSLTAP("cfg","s3station")="500" set ^XTMP("VSLTAP","head")=1,^XTMP("VSLTAP","tail")=0,^XTMP("VSLTAP","data",1)="ONELINE" set n=$$drain^VSLS3(.res) kill ^XTMP("VSLTAP"),^VSLTAP("cfg") merge ^XTMP("VSLTAP")=save merge ^VSLTAP("cfg")=csave do eq^STDASSERT(.pass,.fail,n,1,"capture-sink seam drains the 1-record ring without a live PUT (status 200)")
        quit
        ;
tExampleEnvelope(pass,fail)     ;@TEST "example: VSLS3.envelope"
        new rec,opt,line,t set rec("direction")="resp",rec("call_id")="500-1-7",rec("seq")=7,rec("payload")="hello world" set line=$$envelope^VSLS3(.rec,.opt) do true^STDASSERT(.pass,.fail,$$parse^STDJSON(line,.t),"the line is well-formed JSON") do eq^STDASSERT(.pass,.fail,$$valueOf^STDJSON(t("payload")),"hello world","payload round-trips byte-exact")
        quit
        ;
tExampleEnvelope2(pass,fail)    ;@TEST "example: VSLS3.envelope"
        new rec,opt,line,t set rec("direction")="resp",rec("call_id")="500-1-7",rec("seq")=7,rec("payload")="x" set line=$$envelope^VSLS3(.rec,.opt) do true^STDASSERT(.pass,.fail,$$parse^STDJSON(line,.t),"well-formed") do eq^STDASSERT(.pass,.fail,$$valueOf^STDJSON(t("event_id")),"500-1-7:resp","event_id = call_id ':' direction")
        quit
        ;
tExampleEnvelope3(pass,fail)    ;@TEST "example: VSLS3.envelope"
        new rec,opt,line,t set rec("direction")="resp",rec("call_id")="500-1-7",rec("seq")=7,rec("payload")="hello world" set line=$$envelope^VSLS3(.rec,.opt) do true^STDASSERT(.pass,.fail,$$parse^STDJSON(line,.t),"well-formed") do eq^STDASSERT(.pass,.fail,$$valueOf^STDJSON(t("wire_len")),11,"wire_len = byte length of the RAW payload")
        quit
        ;
tExampleEnvelope4(pass,fail)    ;@TEST "example: VSLS3.envelope"
        new rec,opt,line,t set rec("direction")="req",rec("call_id")="500-1-8",rec("seq")=8,rec("denied")=1,rec("payload")="p" set line=$$envelope^VSLS3(.rec,.opt) do true^STDASSERT(.pass,.fail,$$parse^STDJSON(line,.t),"well-formed") do eq^STDASSERT(.pass,.fail,$$valueOf^STDJSON(t("denied")),1,"a req carries denied, not result_kind")
        quit
        ;
tExampleEnvelope5(pass,fail)    ;@TEST "example: VSLS3.envelope"
        new rec,opt,line,t set rec("direction")="resp",rec("call_id")="500-1-9",rec("seq")=9,rec("payload")="v" set line=$$envelope^VSLS3(.rec,.opt) do true^STDASSERT(.pass,.fail,$$parse^STDJSON(line,.t),"well-formed") do eq^STDASSERT(.pass,.fail,$$valueOf^STDJSON(t("result_kind")),"scalar","a resp carries result_kind, not denied")
        quit
        ;
tExampleEnvelope6(pass,fail)    ;@TEST "example: VSLS3.envelope"
        new rec,opt,line,t set rec("direction")="resp",rec("call_id")="500-1-7",rec("seq")=7,rec("payload")=("a"_$char(9)_"b"_""""_"q") set opt("base64")=1 set line=$$envelope^VSLS3(.rec,.opt) do true^STDASSERT(.pass,.fail,$$parse^STDJSON(line,.t),"well-formed") do eq^STDASSERT(.pass,.fail,$$decode^STDB64($$valueOf^STDJSON(t("payload"))),"a"_$char(9)_"b"_""""_"q","base64 switch decodes byte-exact")
        quit
        ;
tExampleEnvelope7(pass,fail)    ;@TEST "example: VSLS3.envelope"
        new rec,opt,a,b set rec("direction")="resp",rec("call_id")="500-1-7",rec("seq")=7,rec("payload")="hello world" set a=$$envelope^VSLS3(.rec,.opt),b=$$envelope^VSLS3(.rec,.opt) do eq^STDASSERT(.pass,.fail,a,b,"deterministic: same fixture frames byte-identical (M-collation key order)")
        quit
        ;
tExampleFidelityKey(pass,fail)  ;@TEST "example: VSLS3.fidelityKey"
        do eq^STDASSERT(.pass,.fail,$$fidelityKey^VSLS3("500","20260619"),"traffic/500/_fidelity/2026/06/19.json","example: VSLS3.fidelityKey")
        quit
        ;
tExampleGSerialize(pass,fail)   ;@TEST "example: VSLS3.gSerialize"
        new save,b merge save=^XTMP("VSLTAP","data",991,"g") kill ^XTMP("VSLTAP","data",991,"g") set ^XTMP("VSLTAP","data",991,"g","DPT",1)="ONE",^XTMP("VSLTAP","data",991,"g","DPT",2)="TWO" set b=$$gSerialize^VSLS3(991) kill ^XTMP("VSLTAP","data",991,"g") merge ^XTMP("VSLTAP","data",991,"g")=save do eq^STDASSERT(.pass,.fail,$length(b,$char(10)),2,"one JSON node line per descendant of the g MERGE snapshot")
        quit
        ;
tExampleKey(pass,fail)          ;@TEST "example: VSLS3.key"
        do eq^STDASSERT(.pass,.fail,$$key^VSLS3("500","rpc",42,"20260619"),"traffic/500/rpc/2026/06/19/42.ndjson","example: VSLS3.key")
        quit
        ;
tExampleKey2(pass,fail)         ;@TEST "example: VSLS3.key"
        do eq^STDASSERT(.pass,.fail,$$key^VSLS3("442","hl7",1,"20260101"),"traffic/442/hl7/2026/01/01/1.ndjson","example: VSLS3.key")
        quit
        ;
tExampleOffWindowsKey(pass,fail) ;@TEST "example: VSLS3.offWindowsKey"
        do eq^STDASSERT(.pass,.fail,$$offWindowsKey^VSLS3("500","20260619"),"traffic/500/_offwindows/2026/06/19.json","example: VSLS3.offWindowsKey")
        quit
        ;
tExampleResolveRec(pass,fail)   ;@TEST "example: VSLS3.resolveRec"
        new erec,save merge save=^XTMP("VSLTAP") kill ^XTMP("VSLTAP") set ^XTMP("VSLTAP","data",993)="RAWBYTES" do resolveRec^VSLS3(993,"500","rpc",.erec) kill ^XTMP("VSLTAP") merge ^XTMP("VSLTAP")=save do eq^STDASSERT(.pass,.fail,erec("payload"),"RAWBYTES","a legacy v1 record resolves to a plain payload under the station/proto key (set-then-restore)")
        quit
        ;
