VSLTAPFCEX ; Living examples for VSLTAPFC — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLTAPFC label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleDrops(.pass,.fail)
        do tExampleLastFidelity(.pass,.fail)
        do tExampleManifest(.pass,.fail)
        do tExampleManifest2(.pass,.fail)
        do tExampleMatches(.pass,.fail)
        do tExampleMatches2(.pass,.fail)
        do tExamplePayloadOf(.pass,.fail)
        do tExamplePayloadOf2(.pass,.fail)
        do tExamplePayloadOf3(.pass,.fail)
        do tExamplePersist(.pass,.fail)
        do tExampleReconcile(.pass,.fail)
        do tExampleReconcile2(.pass,.fail)
        do tExampleVerify(.pass,.fail)
        do tExampleVerify2(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleDrops(pass,fail)        ;@TEST "example: VSLTAPFC.drops"
        new envs,res,rq,rs,oq,os,rd,od,re,oe set rq("direction")="req",rq("call_id")="A",rq("seq")=1,rq("denied")=0,rq("payload")="p" set envs(1)=$$envelope^VSLS3(.rq,.oq) set rs("direction")="resp",rs("call_id")="A",rs("seq")=2,rs("payload")="r" set envs(2)=$$envelope^VSLS3(.rs,.os) set rd("direction")="req",rd("call_id")="B",rd("seq")=3,rd("denied")=1,rd("payload")="p" set envs(3)=$$envelope^VSLS3(.rd,.od) set re("direction")="req",re("call_id")="C",re("seq")=4,re("denied")=0,re("payload")="p" set envs(4)=$$envelope^VSLS3(.re,.oe) do eq^STDASSERT(.pass,.fail,$$drops^VSLTAPFC(.envs,.res)_"|"_res("rpc_denied")_"|"_res("rpc_error"),"2|1|1","a denied req-no-resp is rpc_denied, an errored req-no-resp is rpc_error, the clean pair is not a drop")
        quit
        ;
tExampleLastFidelity(pass,fail) ;@TEST "example: VSLTAPFC.lastFidelity"
        new res,save,had set had=$data(^VSLTAP("fc","last")),save=$get(^VSLTAP("fc","last")) set res("matched")=5,res("mismatch")=0,res("missing")=0,res("extra")=0 do persist^VSLTAPFC(.res,"65800,1") do true^STDASSERT(.pass,.fail,$$lastFidelity^VSLTAPFC()'="","after a persisted run lastFidelity returns the stored manifest line") if had set ^VSLTAP("fc","last")=save
        quit
        ;
tExampleManifest(pass,fail)     ;@TEST "example: VSLTAPFC.manifest"
        new res,t set res("matched")=10,res("mismatch")=0,res("missing")=0,res("extra")=0 do true^STDASSERT(.pass,.fail,$$parse^STDJSON($$manifest^VSLTAPFC(.res,"65800,43200"),.t)&($$valueOf^STDJSON(t("matched"))=10)&($$type^STDJSON(t("ok"))="true"),"a clean run serialises to well-formed JSON with matched=10 and ok=true")
        quit
        ;
tExampleManifest2(pass,fail)    ;@TEST "example: VSLTAPFC.manifest"
        new res,t set res("matched")=3,res("mismatch")=2,res("missing")=0,res("extra")=0 do eq^STDASSERT(.pass,.fail,$$parse^STDJSON($$manifest^VSLTAPFC(.res,"65800,43200"),.t)_"|"_$$type^STDJSON(t("ok")),"1|false","a run with a mismatch serialises ok=false")
        quit
        ;
tExampleMatches(pass,fail)      ;@TEST "example: VSLTAPFC.matches"
        new rec,opt,line set rec("direction")="resp",rec("call_id")="500-1-5",rec("seq")=5,rec("payload")="hello world" set line=$$envelope^VSLS3(.rec,.opt) do true^STDASSERT(.pass,.fail,$$matches^VSLTAPFC(line,"hello world"),"decoded payload byte-equals the source AND the hash is intact")
        quit
        ;
tExampleMatches2(pass,fail)     ;@TEST "example: VSLTAPFC.matches"
        new rec,opt,line set rec("direction")="resp",rec("call_id")="500-1-5",rec("seq")=5,rec("payload")="hello world" set line=$$envelope^VSLS3(.rec,.opt) do eq^STDASSERT(.pass,.fail,$$matches^VSLTAPFC(line,"hello WORLD"),0,"any drift from the source fails byte-equality")
        quit
        ;
tExamplePayloadOf(pass,fail)    ;@TEST "example: VSLTAPFC.payloadOf"
        new rec,opt,line set rec("direction")="resp",rec("call_id")="500-1-1",rec("seq")=1,rec("payload")=("a"_$char(9)_"b\c"_""""_"q") set line=$$envelope^VSLS3(.rec,.opt) do eq^STDASSERT(.pass,.fail,$$payloadOf^VSLTAPFC(line),"a"_$char(9)_"b\c"_""""_"q","inline payload decodes byte-exact")
        quit
        ;
tExamplePayloadOf2(pass,fail)   ;@TEST "example: VSLTAPFC.payloadOf"
        new rec,opt,line set rec("direction")="resp",rec("call_id")="500-1-1",rec("seq")=1,rec("payload")=("a"_$char(9)_"b"_""""_"q") set opt("base64")=1 set line=$$envelope^VSLS3(.rec,.opt) do eq^STDASSERT(.pass,.fail,$$payloadOf^VSLTAPFC(line),"a"_$char(9)_"b"_""""_"q","base64 payload decodes byte-exact")
        quit
        ;
tExamplePayloadOf3(pass,fail)   ;@TEST "example: VSLTAPFC.payloadOf"
        do eq^STDASSERT(.pass,.fail,$$payloadOf^VSLTAPFC("not json at all"),"","example: VSLTAPFC.payloadOf")
        quit
        ;
tExamplePersist(pass,fail)      ;@TEST "example: VSLTAPFC.persist"
        new res,t,save,had set had=$data(^VSLTAP("fc","last")),save=$get(^VSLTAP("fc","last")) set res("matched")=8,res("mismatch")=0,res("missing")=0,res("extra")=0 do persist^VSLTAPFC(.res,"65800,43200") do eq^STDASSERT(.pass,.fail,$$parse^STDJSON($$lastFidelity^VSLTAPFC(),.t)_"|"_$$valueOf^STDJSON(t("matched")),"1|8","persist stores a readable manifest carrying the matched count") if had set ^VSLTAP("fc","last")=save
        quit
        ;
tExampleReconcile(pass,fail)    ;@TEST "example: VSLTAPFC.reconcile"
        new corpus,envs,res,r1,r2,o1,o2 set corpus(1)="record-1",corpus(2)="record-2" set r1("direction")="resp",r1("call_id")="c1",r1("seq")=1,r1("payload")="record-1" set envs(1)=$$envelope^VSLS3(.r1,.o1) set r2("direction")="resp",r2("call_id")="c2",r2("seq")=2,r2("payload")="record-2" set envs(2)=$$envelope^VSLS3(.r2,.o2) do true^STDASSERT(.pass,.fail,$$reconcile^VSLTAPFC(.corpus,.envs,.res),"a faithful round-trip reconciles fully")
        quit
        ;
tExampleReconcile2(pass,fail)   ;@TEST "example: VSLTAPFC.reconcile"
        new corpus,envs,res,r1,o1 set corpus(1)="record-1",corpus(2)="record-2" set r1("direction")="resp",r1("call_id")="c1",r1("seq")=1,r1("payload")="record-1" set envs(1)=$$envelope^VSLS3(.r1,.o1) do eq^STDASSERT(.pass,.fail,$$reconcile^VSLTAPFC(.corpus,.envs,.res)_"|"_res("matched")_"|"_res("missing"),"0|1|1","a dropped record (seq 2) is flagged missing, reconcile fails")
        quit
        ;
tExampleVerify(pass,fail)       ;@TEST "example: VSLTAPFC.verify"
        new rec,opt,line set rec("direction")="resp",rec("call_id")="500-1-7",rec("seq")=7,rec("payload")="hello world" set line=$$envelope^VSLS3(.rec,.opt) do true^STDASSERT(.pass,.fail,$$verify^VSLTAPFC(line),"a faithfully shipped payload re-hashes to its own sha256 anchor")
        quit
        ;
tExampleVerify2(pass,fail)      ;@TEST "example: VSLTAPFC.verify"
        do eq^STDASSERT(.pass,.fail,$$verify^VSLTAPFC("not a json envelope"),0,"example: VSLTAPFC.verify")
        quit
        ;
