VSLTAPBOEX ; Living examples for VSLTAPBO — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLTAPBO label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleBackout(.pass,.fail)
        do tExampleCleanParams(.pass,.fail)
        do tExampleCleanState(.pass,.fail)
        do tExampleCleanTasks(.pass,.fail)
        do tExampleDelParam(.pass,.fail)
        do tExampleDequeue(.pass,.fail)
        do tExampleParams(.pass,.fail)
        do tExampleParams2(.pass,.fail)
        do tExampleParamsResidue(.pass,.fail)
        do tExampleVerifyClean(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleBackout(pass,fail)      ;@TEST "example: VSLTAPBO.backout"
        set ^XTMP("VSLTAP","data",1)="rec",^VSLTAP("hb")=$horolog do backout^VSLTAPBO() do true^STDASSERT(.pass,.fail,$$verifyClean^VSLTAPBO(.detail),"backout: a seeded footprint verifies clean afterward")
        quit
        ;
tExampleCleanParams(pass,fail)  ;@TEST "example: VSLTAPBO.cleanParams"
        do cleanParams^VSLTAPBO() do true^STDASSERT(.pass,.fail,1,"cleanParams: the fenced XPAR leg returns without raising on a bare engine")
        quit
        ;
tExampleCleanState(pass,fail)   ;@TEST "example: VSLTAPBO.cleanState"
        set ^VSLTAP("cfg","mode")="armed",^XTMP("VSLTAP","data",1)="x" do cleanState^VSLTAPBO() do eq^STDASSERT(.pass,.fail,$data(^VSLTAP)+$data(^XTMP("VSLTAP")),0,"cleanState: both the cache and the control state are gone")
        quit
        ;
tExampleCleanTasks(pass,fail)   ;@TEST "example: VSLTAPBO.cleanTasks"
        do cleanTasks^VSLTAPBO() do true^STDASSERT(.pass,.fail,1,"cleanTasks: the fenced TaskMan leg returns without raising on a bare engine")
        quit
        ;
tExampleDelParam(pass,fail)     ;@TEST "example: VSLTAPBO.delParam"
        do delParam^VSLTAPBO("VSL TAP CAP") do true^STDASSERT(.pass,.fail,1,"delParam: a not-present param is a clean no-op (fenced) on a bare engine")
        quit
        ;
tExampleDequeue(pass,fail)      ;@TEST "example: VSLTAPBO.dequeue"
        do dequeue^VSLTAPBO(0) do true^STDASSERT(.pass,.fail,1,"dequeue: a non-positive task number is a clean no-op")
        quit
        ;
tExampleParams(pass,fail)       ;@TEST "example: VSLTAPBO.params"
        do true^STDASSERT(.pass,.fail,$$params^VSLTAPBO(.out)>0,"params: the tap ships at least one XPAR param")
        quit
        ;
tExampleParams2(pass,fail)      ;@TEST "example: VSLTAPBO.params"
        new out do eq^STDASSERT(.pass,.fail,$$params^VSLTAPBO(.out)_"|"_out(7),"10|VSL S3 ENDPOINT","params: 10 knobs, the 7th is the S3 endpoint")
        quit
        ;
tExampleParamsResidue(pass,fail) ;@TEST "example: VSLTAPBO.paramsResidue"
        do eq^STDASSERT(.pass,.fail,$$paramsResidue^VSLTAPBO(.detail),0,"paramsResidue: a bare engine (no FileMan) reports no surviving XPAR definitions")
        quit
        ;
tExampleVerifyClean(pass,fail)  ;@TEST "example: VSLTAPBO.verifyClean"
        kill ^XTMP("VSLTAP"),^VSLTAP do true^STDASSERT(.pass,.fail,$$verifyClean^VSLTAPBO(.detail),"verifyClean: an empty system verifies clean")
        quit
        ;
