VSLTASKEX ; Living examples for VSLTASK — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLTASK label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExamplePersist(.pass,.fail)
        do tExampleRunning(.pass,.fail)
        do tExampleSchedule(.pass,.fail)
        do tExampleStop(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExamplePersist(pass,fail)      ;@TEST "example: VSLTASK.persist"
        do raises^STDASSERT(.pass,.fail,"set x=$$persist^VSLTASK("""")","U-VSL-TASK-ARG","$$persist with no task# raises U-VSL-TASK-ARG")
        quit
        ;
tExampleRunning(pass,fail)      ;@TEST "example: VSLTASK.running"
        do true^STDASSERT(.pass,.fail,($$running^VSLTASK()=0)!($$running^VSLTASK()=1),"$$running returns a clean boolean (resolves $$TM^%ZTLOAD)")
        quit
        ;
tExampleSchedule(pass,fail)     ;@TEST "example: VSLTASK.schedule"
        do raises^STDASSERT(.pass,.fail,"set x=$$schedule^VSLTASK("""",""ZZ"")","U-VSL-TASK-ARG","$$schedule with no entry raises U-VSL-TASK-ARG")
        quit
        ;
tExampleStop(pass,fail)         ;@TEST "example: VSLTASK.stop"
        do true^STDASSERT(.pass,.fail,$$stop^VSLTASK()=0,"$$stop=0 when not running as a TaskMan task (the cooperative-stop check)")
        quit
        ;
