VSLTAPRUNEX ; Living examples for VSLTAPRUN — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLTAPRUN label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleCadence(.pass,.fail)
        do tExampleFidelityNow(.pass,.fail)
        do tExampleReconcilePersist(.pass,.fail)
        do tExampleRun(.pass,.fail)
        do tExampleSchedule(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleCadence(pass,fail)      ;@TEST "example: VSLTAPRUN.cadence"
        do eq^STDASSERT(.pass,.fail,$$cadence^VSLTAPRUN(),3600,"example: VSLTAPRUN.cadence")
        quit
        ;
tExampleFidelityNow(pass,fail)  ;@TEST "example: VSLTAPRUN.fidelityNow"
        do eq^STDASSERT(.pass,.fail,$$fidelityNow^VSLTAPRUN(),-1,"example: VSLTAPRUN.fidelityNow")
        quit
        ;
tExampleReconcilePersist(pass,fail) ;@TEST "example: VSLTAPRUN.reconcilePersist"
        new corpus,envs,rec,opt,save set save=$get(^VSLTAP("fc","last")) set rec("direction")="resp",rec("call_id")="500-1-1",rec("seq")=1,rec("payload")="hello world",corpus(1)="hello world",envs(1)=$$envelope^VSLS3(.rec,.opt) do eq^STDASSERT(.pass,.fail,$$reconcilePersist^VSLTAPRUN(.corpus,.envs),1,"a byte-perfect 1-record sample reconciles ok=true") set ^VSLTAP("fc","last")=save
        quit
        ;
tExampleRun(pass,fail)          ;@TEST "example: VSLTAPRUN.run"
        new save set save=$get(^VSLTAP("fc","last")) do off^VSLTAP() set ^VSLTAP("fc","last")="{""sentinel"":1}" do run^VSLTAPRUN() do eq^STDASSERT(.pass,.fail,$$lastFidelity^VSLTAPFC(),"{""sentinel"":1}","a disabled tap skips the live work and leaves the last result untouched") set ^VSLTAP("fc","last")=save
        quit
        ;
tExampleSchedule(pass,fail)     ;@TEST "example: VSLTAPRUN.schedule"
        do eq^STDASSERT(.pass,.fail,$$schedule^VSLTAPRUN(),0,"example: VSLTAPRUN.schedule")
        quit
        ;
