VSLTAPEX ; Living examples for VSLTAP — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLTAP label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleAppend(.pass,.fail)
        do tExampleAppend2(.pass,.fail)
        do tExampleAppend3(.pass,.fail)
        do tExampleAppendRec(.pass,.fail)
        do tExampleAppendRec2(.pass,.fail)
        do tExampleArm(.pass,.fail)
        do tExampleArm2(.pass,.fail)
        do tExampleCaptureOn(.pass,.fail)
        do tExampleCaptureOn2(.pass,.fail)
        do tExampleCfg(.pass,.fail)
        do tExampleCfg2(.pass,.fail)
        do tExampleChunk(.pass,.fail)
        do tExampleChunk2(.pass,.fail)
        do tExampleDisable(.pass,.fail)
        do tExampleDisable2(.pass,.fail)
        do tExampleDisabled(.pass,.fail)
        do tExampleDisabled2(.pass,.fail)
        do tExampleDrainTo(.pass,.fail)
        do tExampleDrainTo2(.pass,.fail)
        do tExampleEnabled(.pass,.fail)
        do tExampleEnabled2(.pass,.fail)
        do tExampleHdr(.pass,.fail)
        do tExampleHdr2(.pass,.fail)
        do tExampleHead(.pass,.fail)
        do tExampleHead2(.pass,.fail)
        do tExampleHealthy(.pass,.fail)
        do tExampleHealthy2(.pass,.fail)
        do tExampleHealthy3(.pass,.fail)
        do tExampleHeartbeat(.pass,.fail)
        do tExampleIsV2(.pass,.fail)
        do tExampleIsV22(.pass,.fail)
        do tExampleOff(.pass,.fail)
        do tExampleOff2(.pass,.fail)
        do tExampleOffWindows(.pass,.fail)
        do tExampleOffWindows2(.pass,.fail)
        do tExamplePresent(.pass,.fail)
        do tExamplePresent2(.pass,.fail)
        do tExamplePurgeNode(.pass,.fail)
        do tExamplePurgeNode2(.pass,.fail)
        do tExampleRead(.pass,.fail)
        do tExampleRead2(.pass,.fail)
        do tExampleRearm(.pass,.fail)
        do tExampleRearm2(.pass,.fail)
        do tExampleSeedMap(.pass,.fail)
        do tExampleSeedMap2(.pass,.fail)
        do tExampleSetAlwaysOn(.pass,.fail)
        do tExampleSetAlwaysOn2(.pass,.fail)
        do tExampleSetConsumer(.pass,.fail)
        do tExampleSetConsumer2(.pass,.fail)
        do tExampleSize(.pass,.fail)
        do tExampleSize2(.pass,.fail)
        do tExampleState(.pass,.fail)
        do tExampleState2(.pass,.fail)
        do tExampleState3(.pass,.fail)
        do tExampleTail(.pass,.fail)
        do tExampleTail2(.pass,.fail)
        do tExampleTee(.pass,.fail)
        do tExampleTee2(.pass,.fail)
        do tExampleTeeRec(.pass,.fail)
        do tExampleTeeRec2(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleAppend(pass,fail)       ;@TEST "example: VSLTAP.append"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$append^VSLTAP("rpc-record"),1,"captures with no consumer (always-on ring)") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleAppend2(pass,fail)      ;@TEST "example: VSLTAP.append"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("TST^DUZ=1") do eq^STDASSERT(.pass,.fail,$$read^VSLTAP($$head^VSLTAP()),"TST^DUZ=1","the stored record is verbatim (no transform)") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleAppend3(pass,fail)      ;@TEST "example: VSLTAP.append"
        kill ^VSLTAP,^XTMP("VSLTAP") do off^VSLTAP() do eq^STDASSERT(.pass,.fail,$$append^VSLTAP("x"),0,"OFF -> gated, no append") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleAppendRec(pass,fail)    ;@TEST "example: VSLTAP.appendRec"
        kill ^VSLTAP,^XTMP("VSLTAP") set rec("dir")="resp",rec("call_id")="500-1-1",rec("rpc")="ORWPT INFO",rec("payload")="body",rec("result_kind")="scalar" do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$appendRec^VSLTAP(.rec),1,"a rich v2 record is captured when armed") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleAppendRec2(pass,fail)   ;@TEST "example: VSLTAP.appendRec"
        kill ^VSLTAP,^XTMP("VSLTAP") set rec("payload")="body" do off^VSLTAP() do eq^STDASSERT(.pass,.fail,$$appendRec^VSLTAP(.rec),0,"OFF -> gated, no v2 append") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleArm(pass,fail)          ;@TEST "example: VSLTAP.arm"
        kill ^VSLTAP do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$cfg^VSLTAP("mode","off"),"armed","arm sets mode=armed") kill ^VSLTAP
        quit
        ;
tExampleArm2(pass,fail)         ;@TEST "example: VSLTAP.arm"
        kill ^VSLTAP set ^VSLTAP("disabled")="fault" do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$disabled^VSLTAP(),"","arm clears a prior auto-disable") kill ^VSLTAP
        quit
        ;
tExampleCaptureOn(pass,fail)    ;@TEST "example: VSLTAP.captureOn"
        kill ^VSLTAP do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$captureOn^VSLTAP(),1,"armed + clean -> capture ON regardless of consumer") kill ^VSLTAP
        quit
        ;
tExampleCaptureOn2(pass,fail)   ;@TEST "example: VSLTAP.captureOn"
        kill ^VSLTAP do arm^VSLTAP(),disable^VSLTAP("fault") do eq^STDASSERT(.pass,.fail,$$captureOn^VSLTAP(),0,"auto-failover -> capture OFF (fail-safe)") kill ^VSLTAP
        quit
        ;
tExampleCfg(pass,fail)          ;@TEST "example: VSLTAP.cfg"
        do eq^STDASSERT(.pass,.fail,$$cfg^VSLTAP("nosuchkey","fallback"),"fallback","unset key returns the default")
        quit
        ;
tExampleCfg2(pass,fail)         ;@TEST "example: VSLTAP.cfg"
        set ^VSLTAP("cfg","cap")=750 do eq^STDASSERT(.pass,.fail,$$cfg^VSLTAP("cap",1000),750,"a set cfg knob reads back") kill ^VSLTAP("cfg","cap")
        quit
        ;
tExampleChunk(pass,fail)        ;@TEST "example: VSLTAP.chunk"
        kill ^VSLTAP,^XTMP("VSLTAP") set rec("dir")="resp",rec("payload")="chunkbody",rec("result_kind")="scalar" do arm^VSLTAP() set zz=$$appendRec^VSLTAP(.rec) do eq^STDASSERT(.pass,.fail,$$chunk^VSLTAP($$head^VSLTAP(),1),"chunkbody","the first RAW payload chunk reads back verbatim") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleChunk2(pass,fail)       ;@TEST "example: VSLTAP.chunk"
        kill ^XTMP("VSLTAP") do eq^STDASSERT(.pass,.fail,$$chunk^VSLTAP(99,1),"","absent chunk -> empty string")
        quit
        ;
tExampleDisable(pass,fail)      ;@TEST "example: VSLTAP.disable"
        kill ^VSLTAP do arm^VSLTAP(),disable^VSLTAP("pressure") do eq^STDASSERT(.pass,.fail,$$disabled^VSLTAP(),"pressure","disable records the reason") kill ^VSLTAP
        quit
        ;
tExampleDisable2(pass,fail)     ;@TEST "example: VSLTAP.disable"
        kill ^VSLTAP do arm^VSLTAP(),disable^VSLTAP("latency") do true^STDASSERT(.pass,.fail,$$offWindows^VSLTAP(.zo)'<1,"disable opens an off-window (explicit, never silent)") kill ^VSLTAP
        quit
        ;
tExampleDisabled(pass,fail)     ;@TEST "example: VSLTAP.disabled"
        kill ^VSLTAP do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$disabled^VSLTAP(),"","armed/clean -> empty reason") kill ^VSLTAP
        quit
        ;
tExampleDisabled2(pass,fail)    ;@TEST "example: VSLTAP.disabled"
        kill ^VSLTAP do arm^VSLTAP(),disable^VSLTAP("fault") do eq^STDASSERT(.pass,.fail,$$disabled^VSLTAP(),"fault","reports the auto-failover reason") kill ^VSLTAP
        quit
        ;
tExampleDrainTo(pass,fail)      ;@TEST "example: VSLTAP.drainTo"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("r1"),zz=$$append^VSLTAP("r2"),zz=$$append^VSLTAP("r3"),zz=$$append^VSLTAP("r4"),zz=$$append^VSLTAP("r5") do drainTo^VSLTAP(3) do eq^STDASSERT(.pass,.fail,$$size^VSLTAP(),2,"after draining through seq 3, 2 of 5 remain") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleDrainTo2(pass,fail)     ;@TEST "example: VSLTAP.drainTo"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("a") do drainTo^VSLTAP(99) do eq^STDASSERT(.pass,.fail,$$tail^VSLTAP(),$$head^VSLTAP(),"drainTo is bounded to head (never advances past it)") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleEnabled(pass,fail)      ;@TEST "example: VSLTAP.enabled"
        kill ^VSLTAP do arm^VSLTAP(),setConsumer^VSLTAP(1) do eq^STDASSERT(.pass,.fail,$$enabled^VSLTAP(),1,"capture-on + consumer -> egress enabled") kill ^VSLTAP
        quit
        ;
tExampleEnabled2(pass,fail)     ;@TEST "example: VSLTAP.enabled"
        kill ^VSLTAP do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$enabled^VSLTAP(),0,"capture-on but no consumer -> egress gated off") kill ^VSLTAP
        quit
        ;
tExampleHdr(pass,fail)          ;@TEST "example: VSLTAP.hdr"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("flat") do eq^STDASSERT(.pass,.fail,$$hdr^VSLTAP(1,.zo),0,"a v1 record has no v2 header -> 0") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleHdr2(pass,fail)         ;@TEST "example: VSLTAP.hdr"
        kill ^VSLTAP,^XTMP("VSLTAP") set zr=$name(^TMP($job,"V2")),@zr@("a")="x",rec("dir")="resp",rec("rpc")="ORWU GLOBAL",rec("gref")=zr,rec("result_kind")="global" do arm^VSLTAP() set zz=$$appendRec^VSLTAP(.rec) set zz=$$hdr^VSLTAP($$head^VSLTAP(),.zo) do eq^STDASSERT(.pass,.fail,zo("rpc")_"/"_zo("direction")_"/"_zo("schema_version"),"ORWU GLOBAL/resp/1","header parses rpc, direction and schema_version") kill ^VSLTAP,^XTMP("VSLTAP"),@zr
        quit
        ;
tExampleHead(pass,fail)         ;@TEST "example: VSLTAP.head"
        kill ^XTMP("VSLTAP") do eq^STDASSERT(.pass,.fail,$$head^VSLTAP(),0,"empty ring -> head 0")
        quit
        ;
tExampleHead2(pass,fail)        ;@TEST "example: VSLTAP.head"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("a"),zz=$$append^VSLTAP("b") do eq^STDASSERT(.pass,.fail,$$head^VSLTAP(),2,"two appends -> head 2") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleHealthy(pass,fail)      ;@TEST "example: VSLTAP.healthy"
        kill ^VSLTAP do arm^VSLTAP(),heartbeat^VSLTAP() do eq^STDASSERT(.pass,.fail,$$healthy^VSLTAP(),1,"fresh heartbeat -> healthy") kill ^VSLTAP
        quit
        ;
tExampleHealthy2(pass,fail)     ;@TEST "example: VSLTAP.healthy"
        kill ^VSLTAP do arm^VSLTAP() set ^VSLTAP("hb")=0 do eq^STDASSERT(.pass,.fail,$$healthy^VSLTAP(),0,"stale heartbeat -> not healthy") kill ^VSLTAP
        quit
        ;
tExampleHealthy3(pass,fail)     ;@TEST "example: VSLTAP.healthy"
        kill ^VSLTAP do eq^STDASSERT(.pass,.fail,$$healthy^VSLTAP(),0,"absent heartbeat -> not healthy")
        quit
        ;
tExampleHeartbeat(pass,fail)    ;@TEST "example: VSLTAP.heartbeat"
        kill ^VSLTAP do arm^VSLTAP(),heartbeat^VSLTAP() do true^STDASSERT(.pass,.fail,$$healthy^VSLTAP()=1,"a fresh heartbeat -> healthy") kill ^VSLTAP
        quit
        ;
tExampleIsV2(pass,fail)         ;@TEST "example: VSLTAP.isV2"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("flat") do eq^STDASSERT(.pass,.fail,$$isV2^VSLTAP(1),0,"a legacy v1 string record is not v2") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleIsV22(pass,fail)        ;@TEST "example: VSLTAP.isV2"
        kill ^VSLTAP,^XTMP("VSLTAP") set zr=$name(^TMP($job,"V2")),@zr@("a")="x",rec("dir")="resp",rec("gref")=zr,rec("result_kind")="global" do arm^VSLTAP() set zz=$$appendRec^VSLTAP(.rec) do true^STDASSERT(.pass,.fail,$$isV2^VSLTAP($$head^VSLTAP()),"a record with a g child is v2") kill ^VSLTAP,^XTMP("VSLTAP"),@zr
        quit
        ;
tExampleOff(pass,fail)          ;@TEST "example: VSLTAP.off"
        kill ^VSLTAP do arm^VSLTAP(),off^VSLTAP() do eq^STDASSERT(.pass,.fail,$$state^VSLTAP(),"OFF","kill-switch -> state OFF") kill ^VSLTAP
        quit
        ;
tExampleOff2(pass,fail)         ;@TEST "example: VSLTAP.off"
        kill ^VSLTAP do arm^VSLTAP(),off^VSLTAP() do eq^STDASSERT(.pass,.fail,$$captureOn^VSLTAP(),0,"OFF -> capture gate cannot run") kill ^VSLTAP
        quit
        ;
tExampleOffWindows(pass,fail)   ;@TEST "example: VSLTAP.offWindows"
        kill ^VSLTAP do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$offWindows^VSLTAP(.zo),0,"no failover yet -> zero off-windows") kill ^VSLTAP
        quit
        ;
tExampleOffWindows2(pass,fail)  ;@TEST "example: VSLTAP.offWindows"
        kill ^VSLTAP do arm^VSLTAP(),disable^VSLTAP("pressure") set zz=$$offWindows^VSLTAP(.zo) do eq^STDASSERT(.pass,.fail,$piece(zo(1),"^",2),"pressure","the recorded off-window carries its reason") kill ^VSLTAP
        quit
        ;
tExamplePresent(pass,fail)      ;@TEST "example: VSLTAP.present"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("x") do eq^STDASSERT(.pass,.fail,$$present^VSLTAP(1),1,"a committed slot is present") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExamplePresent2(pass,fail)     ;@TEST "example: VSLTAP.present"
        kill ^XTMP("VSLTAP") do eq^STDASSERT(.pass,.fail,$$present^VSLTAP(99),0,"an absent slot is not present")
        quit
        ;
tExamplePurgeNode(pass,fail)    ;@TEST "example: VSLTAP.purgeNode"
        kill ^VSLTAP,^XTMP("VSLTAP") do purgeNode^VSLTAP() do eq^STDASSERT(.pass,.fail,$length($get(^XTMP("VSLTAP",0)),"^"),3,"purge node is purgedate^createdate^description") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExamplePurgeNode2(pass,fail)   ;@TEST "example: VSLTAP.purgeNode"
        kill ^VSLTAP,^XTMP("VSLTAP") do purgeNode^VSLTAP() do true^STDASSERT(.pass,.fail,+$piece(^XTMP("VSLTAP",0),"^",1)'<+$piece(^XTMP("VSLTAP",0),"^",2),"purgedate >= createdate (FileMan internal dates)") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleRead(pass,fail)         ;@TEST "example: VSLTAP.read"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("hello") do eq^STDASSERT(.pass,.fail,$$read^VSLTAP(1),"hello","reads back the verbatim record at seq 1") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleRead2(pass,fail)        ;@TEST "example: VSLTAP.read"
        kill ^XTMP("VSLTAP") do eq^STDASSERT(.pass,.fail,$$read^VSLTAP(99),"","absent seq -> empty string")
        quit
        ;
tExampleRearm(pass,fail)        ;@TEST "example: VSLTAP.rearm"
        kill ^VSLTAP do arm^VSLTAP(),disable^VSLTAP("pressure"),rearm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$disabled^VSLTAP(),"","re-arm clears the disable reason") kill ^VSLTAP
        quit
        ;
tExampleRearm2(pass,fail)       ;@TEST "example: VSLTAP.rearm"
        kill ^VSLTAP do arm^VSLTAP(),disable^VSLTAP("pressure"),rearm^VSLTAP() set zz=$$offWindows^VSLTAP(.zo) do true^STDASSERT(.pass,.fail,$piece(zo(1),"^",3)'="","re-arm closes the off-window (sets the close stamp)") kill ^VSLTAP
        quit
        ;
tExampleSeedMap(pass,fail)      ;@TEST "example: VSLTAP.seedMap"
        new m do eq^STDASSERT(.pass,.fail,$$seedMap^VSLTAP(.m),9,"nine param->cfg mappings")
        quit
        ;
tExampleSeedMap2(pass,fail)     ;@TEST "example: VSLTAP.seedMap"
        new m,n set n=$$seedMap^VSLTAP(.m) do eq^STDASSERT(.pass,.fail,m(1,"param")_"="_m(1,"cfg"),"VSL TAP CAP=cap","first row maps the CAP param to the cap key")
        quit
        ;
tExampleSetAlwaysOn(pass,fail)  ;@TEST "example: VSLTAP.setAlwaysOn"
        kill ^VSLTAP do setAlwaysOn^VSLTAP(1) do eq^STDASSERT(.pass,.fail,$$cfg^VSLTAP("alwayson",0),1,"the legacy flag is still written/readable") kill ^VSLTAP
        quit
        ;
tExampleSetAlwaysOn2(pass,fail) ;@TEST "example: VSLTAP.setAlwaysOn"
        kill ^VSLTAP do arm^VSLTAP(),setAlwaysOn^VSLTAP(0) do eq^STDASSERT(.pass,.fail,$$captureOn^VSLTAP(),1,"SUBSUMED: alwayson=0 no longer gates the always-on ring") kill ^VSLTAP
        quit
        ;
tExampleSetConsumer(pass,fail)  ;@TEST "example: VSLTAP.setConsumer"
        kill ^VSLTAP do arm^VSLTAP(),setConsumer^VSLTAP(1) do eq^STDASSERT(.pass,.fail,$$enabled^VSLTAP(),1,"consumer present -> egress enabled") kill ^VSLTAP
        quit
        ;
tExampleSetConsumer2(pass,fail) ;@TEST "example: VSLTAP.setConsumer"
        kill ^VSLTAP do arm^VSLTAP(),setConsumer^VSLTAP(0) do eq^STDASSERT(.pass,.fail,$$enabled^VSLTAP(),0,"no consumer -> egress gated off") kill ^VSLTAP
        quit
        ;
tExampleSize(pass,fail)         ;@TEST "example: VSLTAP.size"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set zz=$$append^VSLTAP("a") do eq^STDASSERT(.pass,.fail,$$size^VSLTAP(),1,"one record -> size 1") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleSize2(pass,fail)        ;@TEST "example: VSLTAP.size"
        kill ^XTMP("VSLTAP") do eq^STDASSERT(.pass,.fail,$$size^VSLTAP(),0,"empty ring -> size 0")
        quit
        ;
tExampleState(pass,fail)        ;@TEST "example: VSLTAP.state"
        kill ^VSLTAP do eq^STDASSERT(.pass,.fail,$$state^VSLTAP(),"OFF","unconfigured -> OFF")
        quit
        ;
tExampleState2(pass,fail)       ;@TEST "example: VSLTAP.state"
        kill ^VSLTAP do arm^VSLTAP(),heartbeat^VSLTAP(),setConsumer^VSLTAP(1) do eq^STDASSERT(.pass,.fail,$$state^VSLTAP(),"ACTIVE","armed + healthy + consumer -> ACTIVE") kill ^VSLTAP
        quit
        ;
tExampleState3(pass,fail)       ;@TEST "example: VSLTAP.state"
        kill ^VSLTAP do arm^VSLTAP(),heartbeat^VSLTAP(),disable^VSLTAP("latency") do eq^STDASSERT(.pass,.fail,$$state^VSLTAP(),"AUTO-DISABLED","failover -> AUTO-DISABLED") kill ^VSLTAP
        quit
        ;
tExampleTail(pass,fail)         ;@TEST "example: VSLTAP.tail"
        kill ^XTMP("VSLTAP") do eq^STDASSERT(.pass,.fail,$$tail^VSLTAP(),0,"empty ring -> tail 0")
        quit
        ;
tExampleTail2(pass,fail)        ;@TEST "example: VSLTAP.tail"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() set ^VSLTAP("cfg","cap")=2,zz=$$append^VSLTAP("r1"),zz=$$append^VSLTAP("r2"),zz=$$append^VSLTAP("r3"),zz=$$append^VSLTAP("r4") do eq^STDASSERT(.pass,.fail,$$tail^VSLTAP(),2,"cap=2 after 4 appends -> tail advanced to 2 (oldest 2 dropped)") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleTee(pass,fail)          ;@TEST "example: VSLTAP.tee"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$tee^VSLTAP("rec"),1,"tee adapts to $$append -> 1 when armed") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleTee2(pass,fail)         ;@TEST "example: VSLTAP.tee"
        kill ^VSLTAP,^XTMP("VSLTAP") do off^VSLTAP() do eq^STDASSERT(.pass,.fail,$$tee^VSLTAP("rec"),0,"tee returns 0 when gated off") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleTeeRec(pass,fail)       ;@TEST "example: VSLTAP.teeRec"
        kill ^VSLTAP,^XTMP("VSLTAP") set rec("payload")="b",rec("result_kind")="scalar" do arm^VSLTAP() do eq^STDASSERT(.pass,.fail,$$teeRec^VSLTAP(.rec),1,"teeRec adapts to $$appendRec -> 1 when armed") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
tExampleTeeRec2(pass,fail)      ;@TEST "example: VSLTAP.teeRec"
        kill ^VSLTAP,^XTMP("VSLTAP") set rec("payload")="b" do off^VSLTAP() do eq^STDASSERT(.pass,.fail,$$teeRec^VSLTAP(.rec),0,"teeRec returns 0 when gated off") kill ^VSLTAP,^XTMP("VSLTAP")
        quit
        ;
