VSLRPCTAPEX ; Living examples for VSLRPCTAP — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLRPCTAP label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleCallId(.pass,.fail)
        do tExampleCapture(.pass,.fail)
        do tExampleNakedRef(.pass,.fail)
        do tExampleWork(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleCallId(pass,fail)       ;@TEST "example: VSLRPCTAP.callId"
        do eq^STDASSERT(.pass,.fail,$$callId^VSLRPCTAP("500",7),"500-"_$job_"-7","callId builds station-$J-counter")
        quit
        ;
tExampleCapture(pass,fail)      ;@TEST "example: VSLRPCTAP.capture"
        new rec do off^VSLTAP(),arm^VSLTAP() kill ^XTMP("VSLTAP") set rec("dir")="resp",rec("call_id")="500-1-1",rec("rpc")="ORWU DT",rec("payload")="DUZ=10^NOW" do capture^VSLRPCTAP(.rec) do eq^STDASSERT(.pass,.fail,$$size^VSLTAP(),1,"capture tees one record into the always-on ring") do off^VSLTAP() kill ^XTMP("VSLTAP")
        quit
        ;
tExampleNakedRef(pass,fail)     ;@TEST "example: VSLRPCTAP.nakedRef"
        new zz set zz=$data(^VSLTAP("cfg")) do eq^STDASSERT(.pass,.fail,$$nakedRef^VSLRPCTAP(),"^VSLTAP(""cfg"")","nakedRef returns the caller's last global reference")
        quit
        ;
tExampleWork(pass,fail)         ;@TEST "example: VSLRPCTAP.work"
        new rec do off^VSLTAP(),arm^VSLTAP() kill ^XTMP("VSLTAP") set rec("dir")="resp",rec("call_id")="500-1-1",rec("rpc")="X",rec("payload")="P" do work^VSLRPCTAP(.rec) do eq^STDASSERT(.pass,.fail,$$size^VSLTAP(),1,"work appends the record (the global-touching side)") do off^VSLTAP() kill ^XTMP("VSLTAP")
        quit
        ;
