VSLTAPHLEX ; Living examples for VSLTAPHL — generated from @example tags.
        ; Generated by tools/gen-examples.py — DO NOT EDIT BY HAND.
        ; Source: the VSLTAPHL label @example tags (regenerate with `make examples`).
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tExampleAbcheck(.pass,.fail)
        do tExampleAbcheck2(.pass,.fail)
        do tExampleCanary(.pass,.fail)
        do tExampleCanary2(.pass,.fail)
        do tExamplePctl(.pass,.fail)
        do tExamplePctl2(.pass,.fail)
        do tExampleReady(.pass,.fail)
        do tExampleReady2(.pass,.fail)
        do tExampleRecord(.pass,.fail)
        do tExampleRecord2(.pass,.fail)
        do tExampleRecord3(.pass,.fail)
        do tExampleWatchLatency(.pass,.fail)
        do tExampleWatchLatency2(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tExampleAbcheck(pass,fail)      ;@TEST "example: VSLTAPHL.abcheck"
        kill ^VSLTAP,^XTMP("VSLTAP") set ^VSLTAP("cfg","latbound")=100 do eq^STDASSERT(.pass,.fail,$$abcheck^VSLTAPHL(10,60),0,"tapped-base=50 <= 100 bound -> clean")
        quit
        ;
tExampleAbcheck2(pass,fail)     ;@TEST "example: VSLTAPHL.abcheck"
        kill ^VSLTAP,^XTMP("VSLTAP") set ^VSLTAP("cfg","latbound")=100 do eq^STDASSERT(.pass,.fail,$$abcheck^VSLTAPHL(10,510),1,"tapped-base=500 > 100 bound -> trip")
        quit
        ;
tExampleCanary(pass,fail)       ;@TEST "example: VSLTAPHL.canary"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP(),beat^VSLTAPHL() do true^STDASSERT(.pass,.fail,$$canary^VSLTAPHL()=1,"canary proves capture-substrate works on standby (byte-exact round-trip)")
        quit
        ;
tExampleCanary2(pass,fail)      ;@TEST "example: VSLTAPHL.canary"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP(),beat^VSLTAPHL() set %=$$canary^VSLTAPHL() do eq^STDASSERT(.pass,.fail,$$size^VSLTAP(),0,"the canary leaves the real ring empty (no clinical-traffic perturbation)")
        quit
        ;
tExamplePctl(pass,fail)         ;@TEST "example: VSLTAPHL.pctl"
        new i kill ^VSLTAP,^XTMP("VSLTAP") for i=1:1:100 do record^VSLTAPHL(i,1,0)  do true^STDASSERT(.pass,.fail,($$pctl^VSLTAPHL(50)'<1)&($$pctl^VSLTAPHL(50)'>100),"p50 of 1..100 falls within [1,100]")
        quit
        ;
tExamplePctl2(pass,fail)        ;@TEST "example: VSLTAPHL.pctl"
        new i kill ^VSLTAP,^XTMP("VSLTAP") for i=1:1:100 do record^VSLTAPHL(i,1,0)  do true^STDASSERT(.pass,.fail,$$pctl^VSLTAPHL(95)'<$$pctl^VSLTAPHL(50),"p95 >= p50 (percentiles are monotonic)")
        quit
        ;
tExampleReady(pass,fail)        ;@TEST "example: VSLTAPHL.ready"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP(),beat^VSLTAPHL() do true^STDASSERT(.pass,.fail,$$ready^VSLTAPHL()=1,"readiness probe green while idle (substrate writable, fence armed, heartbeat fresh)")
        quit
        ;
tExampleReady2(pass,fail)       ;@TEST "example: VSLTAPHL.ready"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP(),beat^VSLTAPHL() set ^VSLTAP("hb")=0 do true^STDASSERT(.pass,.fail,$$ready^VSLTAPHL()=0,"a stale heartbeat flips readiness red even with zero traffic")
        quit
        ;
tExampleRecord(pass,fail)       ;@TEST "example: VSLTAPHL.record"
        kill ^VSLTAP,^XTMP("VSLTAP") do record^VSLTAPHL(120,50,0),record^VSLTAPHL(80,40,0),record^VSLTAPHL(0,0,1) do eq^STDASSERT(.pass,.fail,$$writes^VSLTAPHL(),2,"two capture writes counted (the denied sample is not a write)")
        quit
        ;
tExampleRecord2(pass,fail)      ;@TEST "example: VSLTAPHL.record"
        kill ^VSLTAP,^XTMP("VSLTAP") do record^VSLTAPHL(120,50,0),record^VSLTAPHL(80,40,0) do eq^STDASSERT(.pass,.fail,$$bytes^VSLTAPHL(),90,"bytes-to-buffer summed across writes")
        quit
        ;
tExampleRecord3(pass,fail)      ;@TEST "example: VSLTAPHL.record"
        kill ^VSLTAP,^XTMP("VSLTAP") do record^VSLTAPHL(0,0,1) do eq^STDASSERT(.pass,.fail,$$denied^VSLTAPHL(),1,"one consumer-gate denial counted")
        quit
        ;
tExampleWatchLatency(pass,fail) ;@TEST "example: VSLTAPHL.watchLatency"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP(),setConsumer^VSLTAP(1) set ^VSLTAP("cfg","latbound")=100 do watchLatency^VSLTAPHL(10,10) do eq^STDASSERT(.pass,.fail,$$disabled^VSLTAP(),"","a within-bound sample does not disable the tap")
        quit
        ;
tExampleWatchLatency2(pass,fail) ;@TEST "example: VSLTAPHL.watchLatency"
        kill ^VSLTAP,^XTMP("VSLTAP") do arm^VSLTAP(),setConsumer^VSLTAP(1) set ^VSLTAP("cfg","latbound")=100 do watchLatency^VSLTAPHL(10,500) do eq^STDASSERT(.pass,.fail,$$disabled^VSLTAP(),"latency","an over-bound sample self-disables with reason latency")
        quit
        ;
